import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Convergence } from "convergence-ui";
import ClickSpark from "@/components/ClickSpark";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Convergence />
        <Toaster />
        <ClickSpark
          sparkColor="#739072"
          sparkSize={12}
          sparkRadius={26}
          sparkCount={8}
          duration={500}
          easing="ease-out"
          extraScale={1}
        >
          {children}
        </ClickSpark>
      </body>
    </html>
  );
}
